import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/shared/components/Navbar";
import { Footer } from "@/shared/components/Footer";

const interFont = Inter({
  subsets: ["latin"],
  weight: ["800", "600", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${interFont.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
       <Navbar/>
        {children}
       <Footer/>
      </body>
    </html>
  );
}
